- Fix unittest unit/ip/multicast for multicast_address_v6 - Change activation QNX specific changes from -DASIO_QNX to standard definition __QNXNTO__ - Added hook_postmake() for generation shell script to run all unittest on the target (aarch64/x86_64)

diff --git a/asio/build_qnx_GNU/build-hooks b/asio/build_qnx_GNU/build-hooks
--- a/asio/build_qnx_GNU/build-hooks
+++ b/asio/build_qnx_GNU/build-hooks
@@ -5,10 +5,11 @@
 #
 function hook_preconfigure {
 #
-# -DASIO_QNX  is used to solve the incompatibility issue of macros CMSG_SPACE() which is actually calls function __cmsg_alignbytes().
-#        For the tests "fd_passing_stream_server" and "fd_passing_stream_client" it has to be pure pre-compile macros.
+# QNXNTO specific changes are covered by prediefined '__QNXNTO__'
+#       For examples: "fd_passing_stream_server" and "fd_passing_stream_client"
+#       For the testsuites:  unit/ip/multicast 
 #
-	CXXFLAGS="$CXXFLAGS -DASIO_HAS_PTHREADS -DASIO_HAS_STD_STRING_VIEW -DASIO_HAS_CONSTEXPR -DASIO_HAS_STD_FUTURE_CLASS -DASIO_QNX"
+	CXXFLAGS="$CXXFLAGS -DASIO_HAS_PTHREADS -DASIO_HAS_STD_STRING_VIEW -DASIO_HAS_CONSTEXPR -DASIO_HAS_STD_FUTURE_CLASS"
 
 #
 #	Add socket library
@@ -57,8 +58,83 @@ function hook_configure {
 
 function hook_premake {
 	if [ "${make_cmds}" == "check" ] && [ "${TARGET_SYSNAME}" == "nto" ]; then
-		echo For target nto suppress tests execution.
-		echo All tests have to be run on target system.
+		echo "For target nto suppress tests execution."
+		echo "All tests have to be run on target system."
 		make_opts="${make_opts} TESTS=''"
+	fi
+}
+
+function hook_postmake {
+	red="\033[0;31m"
+	grn="\033[0;32m"
+	yel="\033[1;33m"
+	blu="\033[1;34m"
+	cls="\033[0m"
+	base_build=$PWD
+	base_testsuite="src/tests"
+	base_script="run_testsuites.sh"
+	testsuite_log="test-suite.log"
+	testsuite_script=$base_testsuite/$base_script
+
+	if [ "${make_cmds}" == "check" ] && [ "${TARGET_SYSNAME}" == "nto" ] && [ "${SYSNAME}" == "linux" ]; then
+		if [ -d ${base_testsuite} ]; then
+
+			echo "${blu}=========================================================================${cls}"
+			echo "${blu}Generate script to run testsuites for the ${cpu}${cls}"
+			echo "${blu}=========================================================================${cls}"
+
+			echo "Remove old testsuite script ..."
+			echo "rm -f $testsuite_script"
+			rm -f "$testsuite_script"
+						
+			echo "Looking for tests executables..."
+			testsuite_list=$(find . -type f -executable | sed -n "s/^\.\/src\/tests\/\(\S*\)$/\1/p")
+
+			pkg_str=$(grep 'PACKAGE_STRING' Makefile | grep -oP '\d+\.\d+\.\d+' | head -1)
+
+			echo "Creating testsuites script..."
+			echo "#!/bin/sh"       > $testsuite_script || Error "Unexpected error during $testsuite_script initialization";
+			echo "_pass=0"        >> $testsuite_script || Error "Unexpected error during $testsuite_script initialization";
+			echo "_fail=0"        >> $testsuite_script || Error "Unexpected error during $testsuite_script initialization";
+			echo "echo \"### Testsuites log file ###\" > $testsuite_log" >> $testsuite_script || Error "Unexpected error during $testsuite_script initialization";
+			
+
+			echo "Adding testsuites to the script:'$testsuite_script'..."
+			testsuite_number=0
+			for v in ${testsuite_list}; do 
+				testsuite_number=$((testsuite_number+1));
+				echo "### Suite number: $testsuite_number" >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "result=\$($v 2>&1)"                  >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "if [ 0 -eq \$? ]; then"              >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "   _pass=\$((_pass+1))"              >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "   echo \"${grn}PASS${cls}:$v\""     >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "else"                                >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "   _fail=\$((_fail+1))"              >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "   echo \"${red}FAIL${cls}:$v\""     >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "fi"                                  >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "echo \"### Testsuite:$v ###\" >> $testsuite_log" >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "echo \"\${result}\" >> $testsuite_log"           >> $testsuite_script || Error "Unexpected error during $testsuite_script update by testsuite:'$v'";
+				echo "${blu}ADDED${cls}:$v";
+			done
+			
+			echo "echo \"${grn}=========================================================================${cls}\"" >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+			echo "echo \"${grn}Testsuite summary for asio ${pkg_str}${cls}\"" >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+			echo "echo \"${grn}=========================================================================${cls}\"" >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+			echo "echo \"# TOTAL: ${testsuite_number}\""  >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+			echo "echo \"# ${grn}PASS${cls}: \${_pass}\"" >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+			echo "echo \"# ${red}FAIL${cls}: \${_fail}\"" >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+			echo "if [ 0 -eq \${_fail} ]; then"           >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+			echo "echo \"${grn}=========================================================================${cls}\"" >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+			echo "else"                                   >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+			echo "echo \"${red}\${_fail} fails see test log:$testsuite_log ${cls}\"" >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+			echo "fi"                                     >> $testsuite_script || Error "Unexpected error during $testsuite_script update";
+		
+			chmod +x $testsuite_script
+
+			echo "${blu}For asio ${pkg_str} total ${testsuite_number} testsuites were added into script:${testsuite_script}${cls}";
+		else
+			echo "${red}Error - base testsuite:'${base_build}/${base_testsuite}' for asio ${pkg_str} was not found!${cls}";
+			exit 1;
+		fi
 	fi
 }
